### ISSUE TITLE
Why fork?

### ISSUE THREAD

**Issue by cybrann** [JadeCore/TrinityCore#2]
Why did you fork trinitycore?

**Comment by sunshitwowsucks** [comment]
this is 4.3.4 version and we get commits from trinity

**Comment by cybrann** [comment]
I know for 4.3.4 but it's kinda stupid if we fix something our way, then trinity fixes it later and we merge then it brakes.

**Comment by Flameshot** [comment]
@cybrann  I have worked with making my fixes and merging trinitycore fixes too. It is not that hard. If you are a programmer then you know to do it without braking anything.

**Comment by hero2880** [comment]
Look forward to improve!
 now, goblin's  many quests can not complete;
in raids,respawn npcs only open GM mode .

**Comment by sunshitwowsucks** [comment]
create bugtracker report for all bugs found, and we can work on fixing
