### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by Flameshot** [JadeCore/TrinityCore#3]
Maybe this isn't the best way to announce it. I want a way to communicate real time wtih you guys. Like a skype conference or another thing idk. So if you use skype can I have your contact details?

**Comment by cybrann** [comment]
sko.du also we have our chat on skype so I will add you when you send me request.

**Comment by sunshitwowsucks** [comment]
we should make a Discord channel

**Comment by Flameshot** [comment]
Better on skype

**Comment by Keital** [comment]
i dont have acces to skype and bandwith is too low for video calls, a irc channel would be great for me. i go with discord

**Comment by SkyFire** [comment]
New IRC support channel. irc.rizon.net #jadecore

**Comment by Flameshot** [comment]
@Keital but on skype you just chat... idk if you need big bandwidth

**Comment by Keital** [comment]
@Flameshot cant´t enter skype, country access regulations "Access Denied"

**Comment by tarekwiz** [comment]
Hey guys, I would love to help you out with this and the 5.4.8 core

**Comment by Keital** [comment]
@tarekwiz  topic says communication, if youre willing to help send pulls request and dont´t worry cooler will add you anytime.

**Comment by tarekwiz** [comment]
just a quickie. can anybody link me to data files(dbc,..) cuz my client gives corrupted data. Would really appreciate it

**Comment by Keital** [comment]
use extractors

**Comment by tarekwiz** [comment]
My client is corrupted.

**Comment by sunshitwowsucks** [comment]
give me a few mins and i will upload to github

**Comment by sunshitwowsucks** [comment]
https://github.com/JadeCore/TrinityCore/releases

**Comment by tarekwiz** [comment]
thanks a lot man

**Comment by SkyFire** [comment]
I have a IRC setup. I would suggest everyone join it. I will issue ops for the developers. irc.rizon.net #jadecore

**Comment by Keital** [comment]
will close this irc IS our plattform for comms
